
[alias]
ci-fmt = "fmt --all -- --check"
ci-fmt-fix = "fmt --all"
ci-clippy = "lints clippy --all-targets --all-features"
ci-test-compile = "test --no-run --workspace --all-features --no-default-features"
ci-test = "nextest run --all-features --release --workspace --exclude tari_integration_tests --no-fail-fast"
ci-cucumber = "test  --release  --test cucumber --all-features  --package tari_integration_tests -- -t @critical"
ci-check = "check --release --all-targets --workspace --exclude tari_integration_tests --locked"
ci-lcheck = "lcheck --release --all-targets --workspace --exclude tari_integration_tests --locked"
