on: [push, pull_request]

name: Deny

jobs:
  clippy:
    name: deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install components
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Install deny
        run: cargo install cargo-deny
      - name: Run deny
        run: cargo deny check
